defmodule AshReplicant.TestRepo.Migrations.InstallCheckpoint do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ash_replicant_checkpoints, primary_key: false) do
      add(:slot_name, :text, null: false, primary_key: true)
      add(:commit_lsn, :bigint, null: false)
    end

    create unique_index(:ash_replicant_checkpoints, [:slot_name],
             name: "ash_replicant_checkpoints_unique_slot_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:ash_replicant_checkpoints, [:slot_name],
        name: "ash_replicant_checkpoints_unique_slot_index"
      )
    )

    drop(table(:ash_replicant_checkpoints))
  end
end
