defmodule AshReplicant.TestRepo.Migrations.AddDigestKeyState do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ash_replicant_checkpoints) do
      add(:digest_key_state, :binary)
    end
  end

  def down do
    alter table(:ash_replicant_checkpoints) do
      remove(:digest_key_state)
    end
  end
end
