defmodule AshReplicant.TestRepo.Migrations.AddOrderVersions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:order_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:order_id, :text, null: false)
      add(:amount, :text)
      add(:valid_from_lsn, :bigint, null: false)
      add(:valid_to_lsn, :bigint)
      add(:valid_from_ts, :utc_datetime_usec)
      add(:valid_to_ts, :utc_datetime_usec)
      add(:is_current, :boolean, null: false, default: true)
    end

    create index(:order_versions, [:order_id],
             name: "order_versions_open_uniq",
             unique: true,
             where: "valid_to_lsn IS NULL"
           )

    create unique_index(:order_versions, [:order_id, :valid_from_lsn],
             name: "order_versions_order_version_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:order_versions, [:order_id, :valid_from_lsn],
        name: "order_versions_order_version_index"
      )
    )

    drop_if_exists(index(:order_versions, [:order_id], name: "order_versions_open_uniq"))

    drop(table(:order_versions))
  end
end
