defmodule AshReplicant.TestRepo.Migrations.AddMirrorResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:secret_orders, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
      add(:encrypted_pan, :binary)
    end

    create table(:orders, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
      add(:note, :text)
      add(:body, :text)
    end

    create table(:accounts, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
      add(:org_id, :text, null: false)
      add(:name, :text)
    end
  end

  def down do
    drop(table(:accounts))

    drop(table(:orders))

    drop(table(:secret_orders))
  end
end
