defmodule AshReplicant.TestRepo.Migrations.SnapshotProvenanceFixtures do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:snap_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:order_id, :text, null: false)
      add(:amount, :text)
      add(:valid_from_lsn, :bigint, null: false)
      add(:valid_to_lsn, :bigint)
      add(:is_current, :boolean, null: false, default: true)
      add(:replica_fingerprint, :binary)
      add(:replica_seen_attempt, :binary)
    end

    create index(:snap_versions, [:order_id],
             name: "snap_versions_open_uniq",
             unique: true,
             where: "valid_to_lsn IS NULL"
           )

    create unique_index(:snap_versions, [:order_id, :valid_from_lsn],
             name: "snap_versions_snap_version_index"
           )

    create table(:snap_tenant_orders, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
      add(:org_id, :text, null: false)
      add(:note, :text)
      add(:replica_fingerprint, :binary)
      add(:replica_seen_attempt, :binary)
    end

    create table(:snap_orders, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
      add(:note, :text)
      add(:replica_fingerprint, :binary)
      add(:replica_seen_attempt, :binary)
    end
  end

  def down do
    drop(table(:snap_orders))

    drop(table(:snap_tenant_orders))

    drop_if_exists(
      unique_index(:snap_versions, [:order_id, :valid_from_lsn],
        name: "snap_versions_snap_version_index"
      )
    )

    drop_if_exists(index(:snap_versions, [:order_id], name: "snap_versions_open_uniq"))

    drop(table(:snap_versions))
  end
end
