defmodule AshReplicant.TestRepo.Migrations.AddTerminalTombstone do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ash_replicant_checkpoints) do
      add(:terminal_cause, :text)
      add(:terminal_class, :text)
      add(:terminal_at, :utc_datetime_usec)
    end
  end

  def down do
    alter table(:ash_replicant_checkpoints) do
      remove(:terminal_at)
      remove(:terminal_class)
      remove(:terminal_cause)
    end
  end
end
