defmodule AshReplicant.TestRepo.Migrations.SourceBoundCheckpoint do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop(constraint("ash_replicant_checkpoints", "ash_replicant_checkpoints_pkey"))

    alter table(:ash_replicant_checkpoints) do
      modify(:commit_lsn, :bigint, null: true)
      add(:source_system_id, :text, null: false)
      add(:source_database, :text, null: false)
      add(:source_timeline, :bigint)
      add(:publication_contract, :binary)
      add(:publication_fingerprint, :binary)
      add(:snapshot_progress, :binary)
      add(:snapshot_generation, :binary)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    # The shipped unique slot_name index (created by the install migration as the old
    # identity) is KEPT untouched — one bound row per slot is the substrate enforcement
    # of the same-slot-single-source invariant. Codegen's create-then-drop churn for
    # the renamed identity is hand-corrected to a no-op here; the drift gate re-checks.
    create unique_index(
             :ash_replicant_checkpoints,
             [:source_system_id, :source_database, :slot_name],
             name: "ash_replicant_checkpoints_source_slot_index"
           )

    execute(
      "ALTER TABLE \"ash_replicant_checkpoints\" ADD PRIMARY KEY (source_system_id, source_database, slot_name)"
    )
  end

  def down do
    drop(constraint("ash_replicant_checkpoints", "ash_replicant_checkpoints_pkey"))

    drop_if_exists(
      unique_index(:ash_replicant_checkpoints, [:source_system_id, :source_database, :slot_name],
        name: "ash_replicant_checkpoints_source_slot_index"
      )
    )

    alter table(:ash_replicant_checkpoints) do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:snapshot_generation)
      remove(:snapshot_progress)
      remove(:publication_fingerprint)
      remove(:publication_contract)
      remove(:source_timeline)
      remove(:source_database)
      remove(:source_system_id)
      modify(:commit_lsn, :bigint, null: false)
    end

    execute("ALTER TABLE \"ash_replicant_checkpoints\" ADD PRIMARY KEY (slot_name)")
  end
end
