defmodule AshReplicant.TestRepo.Migrations.AddSnapshotIdentityFixture do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:snap_identity_orders, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:external_id, :text, null: false)
      add(:note, :text)
      add(:replica_fingerprint, :binary)
      add(:replica_seen_attempt, :binary)
    end

    create unique_index(:snap_identity_orders, [:external_id],
             name: "snap_identity_orders_external_ref_index"
           )

    # Test-only substrate observer: final-state convergence cannot prove that a
    # retry avoided a second host business action.
    execute("""
    CREATE TRIGGER snap_observe_snap_identity_orders
    AFTER INSERT OR UPDATE OR DELETE ON snap_identity_orders
    FOR EACH ROW EXECUTE FUNCTION snap_observe_effect()
    """)
  end

  def down do
    execute(
      "DROP TRIGGER IF EXISTS snap_observe_snap_identity_orders ON snap_identity_orders"
    )

    drop_if_exists(
      unique_index(:snap_identity_orders, [:external_id],
        name: "snap_identity_orders_external_ref_index"
      )
    )

    drop(table(:snap_identity_orders))
  end
end
