defmodule AshReplicant.TestRepo.Migrations.AddTenantOrder do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tenant_orders, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
      add(:org_id, :text, null: false)
      add(:note, :text)
    end
  end

  def down do
    drop(table(:tenant_orders))
  end
end
